### ISSUE TITLE
Direct acess to post

### ISSUE THREAD

**Issue by EmmanuelBeziat** [ausir0726/nuxt-axios-exercise#1]
Hi,

I just found an issue in your example: https://dist-wmdohkvmis.now.sh/post/V-L%E5%AE%98%E7%B6%B2%E8%A8%AD%E8%A8%88

https://dist-wmdohkvmis.now.sh/posts

If you try to access the post directly from an url, the content won’t load. I think it’s because of the async / await.

I’m currently looking for a workaround, as I’m stuck on the same problem, but the only solution I came up with for now is not very good looking, and too old school.

If you have a nice idea… :)

Thanks!

**Comment by ausir0726** [comment]
hi , is not async function issue

I already report this issue today
https://github.com/nuxt/nuxt.js/issues/420

good news ! , It will be fix .
but , you can't use non English slug , now .

**Comment by EmmanuelBeziat** [comment]
Okay, thanks for the tip.

So my problem is similar, but not related… Strange.

**Comment by ausir0726** [comment]
:D

maybe you can explanation more about your problem .

**Comment by EmmanuelBeziat** [comment]
I just saw it only happen on the generated version…

If you get [here](https://dev.emmanuelbeziat.com/blog/) and click on the first post ("Les resets CSS : à la poubelle"), everything is loaded ; but if you try to refresh the page or directly access it by [its url](https://dev.emmanuelbeziat.com/blog/les-resets-css-a-la-poubelle), the datas won't charge.

I guessed it was because of the async function, but maybe it's totally unrelated.

If you check the post code here: https://github.com/EmmanuelBeziat/emmanuelbeziat/blob/vuejs-static/pages/blog/_slug.vue
You see that I call the data function with async and the axios method with await.

On the index (https://github.com/EmmanuelBeziat/emmanuelbeziat/blob/vuejs-static/pages/blog/index.vue), i do it without any asynchronous statement, and it seems to work fine.

I just don't understand why…

Thanks for your help!

**Comment by ausir0726** [comment]
I think that because you don't give posts array to your `nuxt.config.js` routeParams
you just give a empty array , so it will not generate static page for you .
you need write a http request you api data , then prepare a slug array list ,
then nuxt.js will parse all your posts to static , then you can refresh any page ( only use English slug 😃 )
you can follow this [routeParams with Function which returns a Promise](https://nuxtjs.org/api/configuration-generate/#function-which-returns-a-promise)

I write my solution about prerender static page 
https://github.com/nuxt/nuxt.js/issues/418
hope it will be help you .

**Comment by EmmanuelBeziat** [comment]
This is totally the point. Thanks, many many thanks.
